# -*- coding: utf-8 -*-
"""[ICI4151-1] - Set Covering Problem - Entrega 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T6nWEjnRKyB8GtEfQjd2pT2wVdqPHZ6I
"""

!git clone https://github.com/IgnacioGameolay/TareaOptimizacionFinal

"""# Imports y Parámetros definidos"""

# Imports
import math, random, time
import matplotlib.pyplot as plt
!pip install openpyxl
import openpyxl

# Parámetros definidos
max_iteraciones = 1000  # Máximo de iteraciones del Simulated Annealing
alpha = 0.98  # Valor de enfriamiento
temperatura_inicial = 100  # Temperatura inicial
n_ejecuciones = 10  # Cantidad de ejecuciones para resultados estadísticos

universo = set()
subconjuntos = []

# Semilla base para reproducibilidad. No se usa random.seed() global:
# cada (instancia, ejecución) recibe su propio generador local random.Random(semilla),
# totalmente aislado de los demás.
SEMILLA = 23

# Offset fijo y determinista por instancia. Se usa un diccionario explícito,
# Si se agregan más instancias, basta con sumar una entrada nueva aquí.
OFFSET_INSTANCIA = {
    "Pequeña": 0,
    "Mediana": 1000,
    "Grande": 2000,
}



# Instancia de prueba
instancias_predefinidas = [
    ("Pequeña", "/content/TareaOptimizacionFinal/Instancias/Complejas/01_facil.txt"),
    ("Mediana", "/content/TareaOptimizacionFinal/Instancias/Complejas/02_medio.txt"),
    ("Grande", "/content/TareaOptimizacionFinal/Instancias/Complejas/03_dificil.txt")
]

# Funcion para obtener semmilla determinista reproducible
def obtener_semilla_ejecucion(nombre_instancia, ejecucion):
    #Calcula una semilla determinista y única para cada combinación
    #(instancia, ejecución), independiente del orden de ejecución.

    offset = OFFSET_INSTANCIA.get(nombre_instancia, 9000)
    return SEMILLA + offset + ejecucion

"""# Funciones

## Lectura de instancia SCP
"""

# Lectura de instancia SCP
def leer_instancia_scp(ruta_archivo):
    """
    Lee una instancia SCP desde archivo en formato tipo.

    Formato esperado:
    - n m
    - costos de los m subconjuntos
    - para cada elemento:
        k
        indices de subconjuntos que cubren al elemento

    Retorna:
    - universo: set con elementos {1, 2, ..., n}
    - subconjuntos: lista de tuplas (nombre, elementos, costo)
    """
    with open(ruta_archivo, "r", encoding="utf-8") as f:
        contenido = f.read().split()

    if len(contenido) == 0:
        raise ValueError("El archivo de instancia está vacío.")

    try:
        datos = list(map(int, contenido))
    except ValueError:
        raise ValueError("La instancia contiene valores no enteros.")

    pos = 0

    if len(datos) < 2:
        raise ValueError("Archivo incompleto: faltan n y m.")

    # Primera parte: n y m
    n = datos[pos]
    pos += 1

    m = datos[pos]
    pos += 1

    if n <= 0 or m <= 0:
        raise ValueError("Los valores n y m deben ser positivos.")

    # Segunda parte: costos de los m subconjuntos
    if pos + m > len(datos):
        raise ValueError("Archivo incompleto: faltan costos de subconjuntos.")

    costos = datos[pos:pos + m]
    pos += m

    # Inicializar subconjuntos vacíos
    subconjuntos_elementos = [set() for _ in range(m)]

    # Tercera parte: para cada elemento, leer cuántos subconjuntos lo cubren
    for elemento in range(1, n + 1):
        if pos >= len(datos):
            raise ValueError(
                f"Archivo incompleto al leer cobertura del elemento {elemento}."
            )

        k = datos[pos]
        pos += 1

        if k < 0:
            raise ValueError(
                f"Cantidad inválida de subconjuntos para el elemento {elemento}: {k}."
            )

        if pos + k > len(datos):
            raise ValueError(
                f"Archivo incompleto: el elemento {elemento} dice estar cubierto por {k} subconjuntos, "
                "pero no hay suficientes índices en el archivo."
            )

        indices_subconjuntos = datos[pos:pos + k]
        pos += k

        for idx in indices_subconjuntos:
            if idx < 1 or idx > m:
                raise ValueError(
                    f"Índice de subconjunto fuera de rango: {idx}. "
                    f"Debe estar entre 1 y {m}."
                )

            subconjuntos_elementos[idx - 1].add(elemento)

    universo_leido = set(range(1, n + 1))

    subconjuntos_leidos = [
        (f"S{i + 1}", subconjuntos_elementos[i], costos[i])
        for i in range(m)
    ]

    validar_instancia(universo_leido, subconjuntos_leidos)

    return universo_leido, subconjuntos_leidos


def validar_instancia(universo_leido, subconjuntos_leidos):
    """Verifica que la unión de todos los subconjuntos pueda cubrir el universo."""
    cobertura_total = set()

    for _, elementos, _ in subconjuntos_leidos:
        cobertura_total.update(elementos)

    elementos_no_cubiertos = universo_leido - cobertura_total

    if elementos_no_cubiertos:
        raise ValueError(
            "La instancia no tiene solución factible. "
            f"Elementos no cubiertos: {sorted(elementos_no_cubiertos)}"
        )

"""## Funciones de temperatura y generación de vecindario"""

# Función para calcular el enfriamiento conforme avanzamos en las iteraciones
def enfriamiento(temperatura_actual):
    return temperatura_actual * alpha


# Generación de solución inicial mediante una solución aleatoria válida
def generar_solucion_inicial(rng):
    solucion = generar_solucion_aleatoria(rng)

    while not cubre_universo(solucion):
        solucion = generar_solucion_aleatoria(rng)

    return solucion


# Generación de solución aleatoria con el uso de la biblioteca Random
def generar_solucion_aleatoria(rng):
    solucion = []

    for _ in range(len(subconjuntos)):
        if rng.random() < 0.5:
            solucion.append(0)
        else:
            solucion.append(1)

    return solucion


# Generación de vecino mediante la selección aleatoria de un bit, pasándolo de 1->0 o 0->1
def generar_vecino(solucion_actual, rng):
    vecino = solucion_actual.copy()

    indice = rng.randrange(len(vecino))
    vecino[indice] = 1 - vecino[indice]

    return vecino

"""## Funcionex auxiliares - SCP"""

# Cálculo de costo total de una solución
def calcular_costo(solucion):
    costo = 0

    for i in range(len(subconjuntos)):
        if solucion[i] == 1:
            costo += subconjuntos[i][2]

    return costo


# Función para obtener la cobertura de una solución
def obtener_cobertura(solucion):
    cobertura = set()

    for i in range(len(subconjuntos)):
        if solucion[i] == 1:
            elementos = subconjuntos[i][1]
            cobertura.update(elementos)

    return cobertura


# Función para verificar que los subconjuntos cubran el universo
def cubre_universo(solucion):
    cobertura = obtener_cobertura(solucion)

    return universo.issubset(cobertura)

"""## Funciones de Simulated Annealing y Criterio de Metrópolis"""

# Función que usa Criterio de Metropolis visto en clase,
# con rechazo automático si la solución no cubre el universo
def criterio_aceptacion(solucion_nueva, solucion_antigua, temperatura, rng):
    if not cubre_universo(solucion_nueva):
        return False

    diferencia_costos = calcular_costo(solucion_nueva) - calcular_costo(solucion_antigua)

    if diferencia_costos < 0:
        return True

    if temperatura == 0:
        return False

    p = math.exp(-diferencia_costos / temperatura)

    if rng.random() < p:
        return True

    return False

# Función simulated_annealing para la búsqueda de la mejor solución
def simulated_annealing(solucion_inicial, temperatura_inicial, rng):
    iteracion_actual = 1
    iteracion_mejor_solucion = 1

    solucion_actual = solucion_inicial.copy()
    mejor_solucion = solucion_inicial.copy()

    temperatura_actual = temperatura_inicial

    historial_convergencia = []
    historial_convergencia.append(calcular_costo(mejor_solucion))

    while iteracion_actual <= max_iteraciones:
        vecino = generar_vecino(solucion_actual, rng)

        aceptar_solucion = criterio_aceptacion(
            vecino,
            solucion_actual,
            temperatura_actual,
            rng
        )

        if aceptar_solucion:
            solucion_actual = vecino.copy()

            if calcular_costo(solucion_actual) < calcular_costo(mejor_solucion):
                mejor_solucion = solucion_actual.copy()
                iteracion_mejor_solucion = iteracion_actual

        historial_convergencia.append(calcular_costo(mejor_solucion))

        temperatura_actual = enfriamiento(temperatura_actual)
        iteracion_actual += 1

    return mejor_solucion, iteracion_mejor_solucion, historial_convergencia

"""## Funciones para Graficar Convergencia"""

"""# Funciones para Graficar Resultados y Convergencia"""

# Función para guardar el detalle de convergencia en CSV
def guardar_convergencia_csv(resumenes, ruta_salida):
    encabezados = [
        "instancia",
        "ejecucion",
        "iteracion",
        "mejor_costo"
    ]

    with open(ruta_salida, "w", encoding="utf-8") as f:
        f.write(",".join(encabezados) + "\n")

        for resumen in resumenes:
            instancia = resumen["instancia"]
            historiales = resumen["historiales_convergencia"]

            for i in range(len(historiales)):
                ejecucion = i + 1
                historial = historiales[i]

                for iteracion in range(len(historial)):
                    fila = [
                        instancia,
                        ejecucion,
                        iteracion,
                        historial[iteracion]
                    ]

                    valores = []

                    for valor in fila:
                        valores.append(texto_csv(valor))

                    f.write(",".join(valores) + "\n")


# Función para calcular la convergencia promedio de una instancia
def calcular_convergencia_promedio(historiales):
    largo_minimo = len(historiales[0])
    promedio = []

    for historial in historiales:
        if len(historial) < largo_minimo:
            largo_minimo = len(historial)

    for i in range(largo_minimo):
        suma = 0

        for historial in historiales:
            suma += historial[i]

        promedio.append(suma / len(historiales))

    return promedio


# Función para limpiar nombres de archivo
def limpiar_nombre_archivo(nombre):
    nombre_limpio = ""

    for caracter in nombre:
        if caracter.isalnum() or caracter == "_" or caracter == "-":
            nombre_limpio += caracter
        else:
            nombre_limpio += "_"

    return nombre_limpio


# Función para generar gráfico de convergencia por instancia
def graficar_convergencia_instancia(resumen):
    nombre_instancia = resumen["instancia"]
    historiales = resumen["historiales_convergencia"]
    promedio = calcular_convergencia_promedio(historiales)

    plt.figure(figsize=(10, 6))

    for i in range(len(historiales)):
        historial = historiales[i]
        iteraciones = list(range(len(historial)))

        plt.plot(
            iteraciones,
            historial,
            alpha=0.35,
            linewidth=1,
            label=f"Ejecución {i + 1}"
        )

    iteraciones_promedio = list(range(len(promedio)))

    plt.plot(
        iteraciones_promedio,
        promedio,
        linewidth=3,
        label="Promedio"
    )

    plt.title("Convergencia - " + nombre_instancia)
    plt.xlabel("Iteración")
    plt.ylabel("Mejor costo encontrado")
    plt.grid(True)
    plt.legend()
    plt.tight_layout()

    ruta_png = "convergencia_" + limpiar_nombre_archivo(nombre_instancia) + ".png"

    plt.savefig(ruta_png, dpi=300)
    plt.close()

    return ruta_png


# Función para generar gráfico comparativo de convergencia promedio entre instancias
def graficar_convergencia_promedio_instancias(resumenes):
    plt.figure(figsize=(10, 6))

    for resumen in resumenes:
        nombre_instancia = resumen["instancia"]
        historiales = resumen["historiales_convergencia"]
        promedio = calcular_convergencia_promedio(historiales)
        iteraciones = list(range(len(promedio)))

        plt.plot(
            iteraciones,
            promedio,
            linewidth=2,
            label=nombre_instancia
        )

    plt.title("Convergencia promedio por instancia")
    plt.xlabel("Iteración")
    plt.ylabel("Mejor costo promedio")
    plt.grid(True)
    plt.legend()
    plt.tight_layout()

    ruta_png = "convergencia_promedio_instancias.png"

    plt.savefig(ruta_png, dpi=300)
    plt.close()

    return ruta_png


# Función para generar boxplot de costos finales por instancia
def graficar_boxplot_costos(resumenes):
    datos = []
    etiquetas = []

    for resumen in resumenes:
        datos.append(resumen["resultados"])
        etiquetas.append(resumen["instancia"])

    plt.figure(figsize=(8, 6))

    plt.boxplot(datos, tick_labels=etiquetas)

    plt.title("Distribución de costos finales por instancia")
    plt.xlabel("Instancia")
    plt.ylabel("Costo final")
    plt.grid(True)
    plt.tight_layout()

    ruta_png = "boxplot_costos_instancias.png"

    plt.savefig(ruta_png, dpi=300)
    plt.close()

    return ruta_png


# Función para generar gráfico de barras con mejor, media y peor costo
def graficar_resumen_costos(resumenes):
    etiquetas = []
    mejores = []
    medias = []
    peores = []

    for resumen in resumenes:
        etiquetas.append(resumen["instancia"])
        mejores.append(resumen["mejor_costo_global"])
        medias.append(resumen["media"])
        peores.append(resumen["peor_costo"])

    posiciones = list(range(len(etiquetas)))
    ancho = 0.25

    posiciones_mejor = []
    posiciones_media = []
    posiciones_peor = []

    for posicion in posiciones:
        posiciones_mejor.append(posicion - ancho)
        posiciones_media.append(posicion)
        posiciones_peor.append(posicion + ancho)

    plt.figure(figsize=(10, 6))

    plt.bar(posiciones_mejor, mejores, width=ancho, label="Mejor costo")
    plt.bar(posiciones_media, medias, width=ancho, label="Media")
    plt.bar(posiciones_peor, peores, width=ancho, label="Peor costo")

    plt.title("Resumen de costos por instancia")
    plt.xlabel("Instancia")
    plt.ylabel("Costo")
    plt.xticks(posiciones, etiquetas)
    plt.grid(True, axis="y")
    plt.legend()
    plt.tight_layout()

    ruta_png = "resumen_costos_instancias.png"

    plt.savefig(ruta_png, dpi=300)
    plt.close()

    return ruta_png


# Función principal para generar todos los gráficos
def plottear_graficos(resumenes):
    archivos_generados = []

    for resumen in resumenes:
        ruta_png = graficar_convergencia_instancia(resumen)
        archivos_generados.append(ruta_png)

    ruta_convergencia_promedio = graficar_convergencia_promedio_instancias(resumenes)
    archivos_generados.append(ruta_convergencia_promedio)

    ruta_boxplot = graficar_boxplot_costos(resumenes)
    archivos_generados.append(ruta_boxplot)

    ruta_resumen_costos = graficar_resumen_costos(resumenes)
    archivos_generados.append(ruta_resumen_costos)

    return archivos_generados

# Función para mostrar todos los gráficos PNG generados
def mostrar_graficos_generados(archivos_graficos):
    for archivo in archivos_graficos:
        print("\nMostrando gráfico:", archivo)

        imagen = plt.imread(archivo)

        plt.figure(figsize=(10, 6))
        plt.imshow(imagen)
        plt.axis("off")
        plt.title(archivo)
        plt.show()

"""## Funciones de métricas, experimentos y resumen de resultados"""

# Cálculo de media de los resultados
def calcular_media(resultados):
    return sum(resultados) / len(resultados)


# Cálculo de desviación estándar muestral de los resultados
def calcular_desviacion_estandar(resultados):
    if len(resultados) <= 1:
        return 0

    media = calcular_media(resultados)
    suma = 0

    for valor in resultados:
        suma += (valor - media) ** 2

    return math.sqrt(suma / (len(resultados) - 1))


# Función para ejecutar la metaheurística varias veces
def ejecutar_experimentos(nombre_instancia):
    resultados = []
    soluciones = []
    iteraciones_mejor = []
    tiempos_ejecucion = []
    filas_resultados = []
    historiales_convergencia = []

    mejor_solucion_global = None
    mejor_costo_global = None
    mejores_subconjuntos_global = []

    tiempo_inicio_total = time.time()

    for ejecucion in range(1, n_ejecuciones + 1):
        # Generador aleatorio usando la seed determinista
        semilla_actual = obtener_semilla_ejecucion(nombre_instancia, ejecucion)
        rng = random.Random(semilla_actual)

        tiempo_inicio_ejecucion = time.time()

        solucion_inicial = generar_solucion_inicial(rng)

        mejor_solucion, iteracion_mejor, historial_convergencia = simulated_annealing(
            solucion_inicial,
            temperatura_inicial,
            rng
        )

        tiempo_fin_ejecucion = time.time()
        tiempo_total_ejecucion = tiempo_fin_ejecucion - tiempo_inicio_ejecucion

        costo = calcular_costo(mejor_solucion)
        factible = cubre_universo(mejor_solucion)
        subconjuntos_elegidos = obtener_subconjuntos_seleccionados(mejor_solucion)

        resultados.append(costo)
        soluciones.append(mejor_solucion)
        iteraciones_mejor.append(iteracion_mejor)
        tiempos_ejecucion.append(tiempo_total_ejecucion)
        historiales_convergencia.append(historial_convergencia)

        if mejor_costo_global is None or costo < mejor_costo_global:
          mejor_costo_global = costo
          mejor_solucion_global = mejor_solucion.copy()
          mejores_subconjuntos_global = subconjuntos_elegidos.copy()
          semilla_mejor_global = semilla_actual

        fila = {
            "instancia": nombre_instancia,
            "ejecucion": ejecucion,
            "semilla": semilla_actual,
            "costo": costo,
            "subconjuntos_seleccionados": "|".join(subconjuntos_elegidos),
            "factible": factible,
            "tiempo_ejecucion": tiempo_total_ejecucion,
            "iteraciones_usadas": max_iteraciones,
            "iteracion_mejor": iteracion_mejor,
            "vector_binario": "".join(str(x) for x in mejor_solucion),

        }

        filas_resultados.append(fila)

        print(
            f"Instancia = {nombre_instancia}, "
            f"Ejecución {ejecucion}: "
            f"semilla = {semilla_actual}: "
            f"costo = {costo}, "
            f"factible = {factible}, "
            f"tiempo = {round(tiempo_total_ejecucion, 6)}s, "
            f"iteración mejor = {iteracion_mejor}"
        )

    tiempo_total = time.time() - tiempo_inicio_total

    resumen = {
        "instancia": nombre_instancia,
        "resultados": resultados,
        "soluciones": soluciones,
        "iteraciones_mejor": iteraciones_mejor,
        "tiempos_ejecucion": tiempos_ejecucion,
        "filas_resultados": filas_resultados,
        "historiales_convergencia": historiales_convergencia,
        "mejor_solucion_global": mejor_solucion_global,
        "mejor_costo_global": mejor_costo_global,
        "mejores_subconjuntos_global": mejores_subconjuntos_global,
        "semilla_mejor_global": semilla_mejor_global,
        "peor_costo": max(resultados),
        "media": calcular_media(resultados),
        "desviacion_estandar": calcular_desviacion_estandar(resultados),
        "tiempo_promedio": calcular_media(tiempos_ejecucion),
        "tiempo_total": tiempo_total,
    }

    return resumen


# Función para obtener los nombres de los subconjuntos seleccionados
def obtener_subconjuntos_seleccionados(solucion):
    subconjuntos_seleccionados = []

    for i in range(len(subconjuntos)):
        if solucion[i] == 1:
            subconjuntos_seleccionados.append(subconjuntos[i][0])

    return subconjuntos_seleccionados


# Función para imprimir el resumen final
def imprimir_resumen_resultado(resumen):
    mejor_solucion = resumen["mejor_solucion_global"]
    cobertura = obtener_cobertura(mejor_solucion)

    print("\n========== Resumen SCP - Simulated Annealing ==========")
    print("Cantidad de elementos del universo:", len(universo))
    print("Cantidad de subconjuntos:", len(subconjuntos))
    print("Vector binario mejor:", mejor_solucion)
    print("Subconjuntos seleccionados:", resumen["mejores_subconjuntos_global"])
    print("Mejor costo encontrado:", resumen["mejor_costo_global"])
    print("Semilla que produjo la mejor solución:", resumen["semilla_mejor_global"])
    print("Cobertura:", sorted(cobertura))
    print("Elementos cubiertos:", len(cobertura), "/", len(universo))
    print("Factible:", cubre_universo(mejor_solucion))
    print("Valores obtenidos:", resumen["resultados"])
    print("Media:", round(resumen["media"], 4))
    print("Desviación estándar:", round(resumen["desviacion_estandar"], 4))
    print("Iteraciones por ejecución:", max_iteraciones)
    print("Temperatura inicial:", temperatura_inicial)
    print("Alpha/enfriamiento geométrico:", alpha)
    print("Tiempo total de ejecución:", round(resumen["tiempo_total"], 6), "segundos")
    print("=======================================================")

"""## Funciones de guardado de resultados"""

# Función para preparar texto en formato CSV
def texto_csv(valor):
    texto = str(valor)
    texto = texto.replace('"', '""')
    return '"' + texto + '"'


# Función para guardar la tabla de 10 ejecuciones por instancia
def guardar_resultados_csv(filas_resultados, ruta_salida):
    encabezados = [
        "instancia",
        "ejecucion",
        "semilla",
        "costo",
        "subconjuntos_seleccionados",
        "factible",
        "tiempo_ejecucion",
        "iteraciones_usadas",
        "iteracion_mejor",
        "vector_binario",
    ]

    with open(ruta_salida, "w", encoding="utf-8") as f:
        f.write(",".join(encabezados) + "\n")

        for fila in filas_resultados:
            valores = []

            for encabezado in encabezados:
                valores.append(texto_csv(fila[encabezado]))

            f.write(",".join(valores) + "\n")

def guardar_csv_por_instancia(resumenes):

    archivos_generados = []

    encabezados = [
        "instancia",
        "ejecucion",
        "semilla",
        "costo",
        "subconjuntos_seleccionados",
        "factible",
        "tiempo_ejecucion",
        "iteraciones_usadas",
        "iteracion_mejor",
        "vector_binario",
    ]

    for resumen in resumenes:
        nombre = limpiar_nombre_archivo(resumen["instancia"])
        ruta_salida = "resultados_" + nombre + ".csv"

        with open(ruta_salida, "w", encoding="utf-8") as f:
            f.write(",".join(encabezados) + "\n")

            for fila in resumen["filas_resultados"]:
                valores = []
                for encabezado in encabezados:
                    valores.append(texto_csv(fila[encabezado]))
                f.write(",".join(valores) + "\n")

        archivos_generados.append(ruta_salida)
        print("Generado:", ruta_salida)

    return archivos_generados

# Función para guardar la tabla resumen por instancia
def guardar_resumen_csv(resumenes, ruta_salida):
    encabezados = [
        "instancia",
        "mejor_costo",
        "peor_costo",
        "media",
        "desviacion_estandar",
        "tiempo_promedio",
        "tiempo_total",
        "iteraciones",
        "temperatura_inicial",
        "alpha",
        "mejor_vector_binario",
        "mejores_subconjuntos",
    ]

    with open(ruta_salida, "w", encoding="utf-8") as f:
        f.write(",".join(encabezados) + "\n")

        for resumen in resumenes:
            mejor_solucion = resumen["mejor_solucion_global"]

            fila = {
                "instancia": resumen["instancia"],
                "mejor_costo": resumen["mejor_costo_global"],
                "peor_costo": resumen["peor_costo"],
                "media": round(resumen["media"], 4),
                "desviacion_estandar": round(resumen["desviacion_estandar"], 4),
                "tiempo_promedio": round(resumen["tiempo_promedio"], 6),
                "tiempo_total": round(resumen["tiempo_total"], 6),
                "iteraciones": max_iteraciones,
                "temperatura_inicial": temperatura_inicial,
                "alpha": alpha,
                "mejor_vector_binario": "".join(str(x) for x in mejor_solucion),
                "mejores_subconjuntos": "|".join(resumen["mejores_subconjuntos_global"]),
            }

            valores = []

            for encabezado in encabezados:
                valores.append(texto_csv(fila[encabezado]))

            f.write(",".join(valores) + "\n")


def guardar_resultados_xlsx(todos_los_resultados, resumenes):
    """
    Genera resultados.xlsx con tres hojas:
      - Detalle:  una fila por ejecución (todas las instancias)
      - Resumen:  media, desv. est., mejor/peor costo, tiempo promedio por instancia
      - Boxplot:  datos Q1/Q3/mediana para graficar en Excel si se desea
    Requiere openpyxl (pip install openpyxl).
    """
    wb = openpyxl.Workbook()

    # ---- Hoja 1: Detalle ------------------------------------------------
    ws_detalle = wb.active
    ws_detalle.title = "Detalle"

    encabezados_detalle = [
        "instancia", "ejecucion", "semilla", "costo", "subconjuntos_seleccionados",
        "factible", "tiempo_ejecucion", "iteraciones_usadas",
        "iteracion_mejor", "vector_binario",
    ]
    ws_detalle.append(encabezados_detalle)

    for fila in todos_los_resultados:
        ws_detalle.append([fila[col] for col in encabezados_detalle])

    # ---- Hoja 2: Resumen ------------------------------------------------
    ws_resumen = wb.create_sheet("Resumen")

    encabezados_resumen = [
        "instancia", "semilla", "mejor_costo", "peor_costo", "media",
        "desviacion_estandar", "tiempo_promedio", "tiempo_total",
        "iteraciones", "temperatura_inicial", "alpha",
        "mejores_subconjuntos",
    ]
    ws_resumen.append(encabezados_resumen)

    for resumen in resumenes:
        ws_resumen.append([
            resumen["instancia"],
            resumen["semilla_mejor_global"],
            resumen["mejor_costo_global"],
            resumen["peor_costo"],
            round(resumen["media"], 4),
            round(resumen["desviacion_estandar"], 4),
            round(resumen["tiempo_promedio"], 6),
            round(resumen["tiempo_total"], 6),
            max_iteraciones,
            temperatura_inicial,
            alpha,
            "|".join(resumen["mejores_subconjuntos_global"]),
        ])

    # ---- Hoja 3: Boxplot ------------------------------------------------
    ws_boxplot = wb.create_sheet("Boxplot")
    ws_boxplot.append(["instancia", "minimo", "q1", "mediana", "q3", "maximo"])

    for resumen in resumenes:
        minimo, q1, mediana, q3, maximo = calcular_datos_boxplot(resumen["resultados"])
        ws_boxplot.append([resumen["instancia"], minimo, q1, mediana, q3, maximo])

    ruta_xlsx = "resultados.xlsx"
    wb.save(ruta_xlsx)
    print("Generado:", ruta_xlsx)
    return ruta_xlsx



# Función para calcular la mediana
def calcular_mediana(valores):
    valores_ordenados = sorted(valores)
    n = len(valores_ordenados)
    mitad = n // 2

    if n % 2 == 1:
        return valores_ordenados[mitad]

    return (valores_ordenados[mitad - 1] + valores_ordenados[mitad]) / 2


# Función para calcular datos útiles para boxplot
def calcular_datos_boxplot(valores):
    valores_ordenados = sorted(valores)
    n = len(valores_ordenados)

    if n % 2 == 0:
        mitad_inferior = valores_ordenados[:n // 2]
        mitad_superior = valores_ordenados[n // 2:]
    else:
        mitad_inferior = valores_ordenados[:n // 2]
        mitad_superior = valores_ordenados[n // 2 + 1:]

    minimo = min(valores_ordenados)
    q1 = calcular_mediana(mitad_inferior)
    mediana = calcular_mediana(valores_ordenados)
    q3 = calcular_mediana(mitad_superior)
    maximo = max(valores_ordenados)

    return minimo, q1, mediana, q3, maximo


# Función para guardar datos de boxplot en CSV
def guardar_boxplot_csv(resumenes, ruta_salida):
    encabezados = ["instancia", "semilla", "minimo", "q1", "mediana", "q3", "maximo"]

    with open(ruta_salida, "w", encoding="utf-8") as f:
        f.write(",".join(encabezados) + "\n")

        for resumen in resumenes:
            minimo, q1, mediana, q3, maximo = calcular_datos_boxplot(
                resumen["resultados"]
            )

            fila = [
                resumen["instancia"],
                minimo,
                q1,
                mediana,
                q3,
                maximo,
            ]

            valores = []

            for valor in fila:
                valores.append(texto_csv(valor))

            f.write(",".join(valores) + "\n")


# Función para generar un análisis textual breve de los resultados

def guardar_analisis_txt(resumenes, ruta_salida):
    """
    Genera un análisis textual con:
      - Métricas individuales por instancia (estabilidad, calidad)
      - Comparación numérica ENTRE instancias (diferencias de costo y tiempo)
    """
    with open(ruta_salida, "w", encoding="utf-8") as f:

        f.write("Análisis de resultados - Simulated Annealing para SCP\n")
        f.write("=====================================================\n\n")

        # ---- Sección 1: detalle por instancia ---------------------------
        f.write("1. DETALLE POR INSTANCIA\n")
        f.write("------------------------\n\n")

        for resumen in resumenes:
            f.write(f"Instancia: {resumen['instancia']}\n")
            f.write(f"  Valores obtenidos   : {resumen['resultados']}\n")
            f.write(f"  Mejor costo         : {resumen['mejor_costo_global']}\n")
            f.write(f"  Peor costo          : {resumen['peor_costo']}\n")
            f.write(f"  Media               : {round(resumen['media'], 4)}\n")
            f.write(f"  Desviación estándar : {round(resumen['desviacion_estandar'], 4)}\n")
            f.write(f"  Tiempo promedio     : {round(resumen['tiempo_promedio'], 6)} s\n")

            # Estabilidad
            if resumen["desviacion_estandar"] == 0:
                estabilidad = "completamente estable (todos los resultados fueron idénticos)."
            elif resumen["desviacion_estandar"] <= resumen["media"] * 0.05:
                estabilidad = "muy estable (desv. est. <= 5% de la media)."
            elif resumen["desviacion_estandar"] <= resumen["media"] * 0.10:
                estabilidad = "moderadamente estable (desv. est. entre 5% y 10% de la media)."
            else:
                estabilidad = (
                    f"poco estable (desv. est. = "
                    f"{round(resumen['desviacion_estandar'] / resumen['media'] * 100, 1)}% de la media). "
                    "Considerar aumentar iteraciones o ajustar temperatura."
                )

            f.write(f"  Estabilidad         : {estabilidad}\n")

            # Calidad (basada en dispersión mejor/media)
            diferencia_porcentual = (
                (resumen["media"] - resumen["mejor_costo_global"])
                / resumen["mejor_costo_global"] * 100
                if resumen["mejor_costo_global"] > 0 else 0
            )
            if diferencia_porcentual <= 5:
                calidad = "alta: la media se aleja menos del 5% del mejor costo."
            elif diferencia_porcentual <= 15:
                calidad = f"media: la media supera al mejor costo en un {round(diferencia_porcentual, 1)}%."
            else:
                calidad = (
                    f"baja: la media supera al mejor costo en un {round(diferencia_porcentual, 1)}%. "
                    "El algoritmo es inconsistente entre ejecuciones."
                )

            f.write(f"  Calidad de solución : {calidad}\n\n")

        # ---- Sección 2: comparación entre instancias --------------------
        if len(resumenes) > 1:
            f.write("2. COMPARACIÓN ENTRE INSTANCIAS\n")
            f.write("--------------------------------\n\n")

            # Tabla compacta
            f.write(
                f"{'Instancia':<12} {'Mejor':>10} {'Peor':>10} "
                f"{'Media':>10} {'Desv.Est.':>10} {'T.Prom.(s)':>12}\n"
            )
            f.write("-" * 60 + "\n")

            for resumen in resumenes:
                f.write(
                    f"{resumen['instancia']:<12} "
                    f"{resumen['mejor_costo_global']:>10} "
                    f"{resumen['peor_costo']:>10} "
                    f"{round(resumen['media'], 2):>10} "
                    f"{round(resumen['desviacion_estandar'], 2):>10} "
                    f"{round(resumen['tiempo_promedio'], 4):>12}\n"
                )

            f.write("\n")

            # Diferencias numéricas respecto a la instancia de referencia (primera)
            ref = resumenes[0]
            f.write(f"Referencia base: instancia '{ref['instancia']}'\n\n")

            for resumen in resumenes[1:]:
                diff_mejor = resumen["mejor_costo_global"] - ref["mejor_costo_global"]
                diff_media = resumen["media"] - ref["media"]
                diff_tiempo = resumen["tiempo_promedio"] - ref["tiempo_promedio"]

                pct_mejor = (
                    diff_mejor / ref["mejor_costo_global"] * 100
                    if ref["mejor_costo_global"] > 0 else 0
                )
                pct_media = (
                    diff_media / ref["media"] * 100
                    if ref["media"] > 0 else 0
                )

                f.write(f"Instancia '{resumen['instancia']}' vs '{ref['instancia']}':\n")
                f.write(
                    f"  Mejor costo  : {'+' if diff_mejor >= 0 else ''}{diff_mejor} "
                    f"({'+' if pct_mejor >= 0 else ''}{round(pct_mejor, 1)}%)\n"
                )
                f.write(
                    f"  Media        : {'+' if diff_media >= 0 else ''}{round(diff_media, 2)} "
                    f"({'+' if pct_media >= 0 else ''}{round(pct_media, 1)}%)\n"
                )
                f.write(
                    f"  Tiempo prom. : {'+' if diff_tiempo >= 0 else ''}{round(diff_tiempo, 4)} s\n\n"
                )

            # Instancia con mejor y peor desempeño global
            mejor_inst = min(resumenes, key=lambda r: r["mejor_costo_global"])
            peor_inst  = max(resumenes, key=lambda r: r["mejor_costo_global"])
            mas_estable = min(resumenes, key=lambda r: r["desviacion_estandar"])

            f.write("Conclusiones comparativas:\n")
            f.write(
                f"  - Mejor costo global     : instancia '{mejor_inst['instancia']}' "
                f"(costo = {mejor_inst['mejor_costo_global']})\n"
            )
            f.write(
                f"  - Peor costo global      : instancia '{peor_inst['instancia']}' "
                f"(costo = {peor_inst['mejor_costo_global']})\n"
            )
            f.write(
                f"  - Más estable            : instancia '{mas_estable['instancia']}' "
                f"(desv. est. = {round(mas_estable['desviacion_estandar'], 4)})\n"
            )

            # Tendencia de escalabilidad
            costos_medios = [r["media"] for r in resumenes]
            tiempos_medios = [r["tiempo_promedio"] for r in resumenes]

            if all(costos_medios[i] <= costos_medios[i + 1] for i in range(len(costos_medios) - 1)):
                tendencia_costo = "crece monotónicamente con el tamaño de la instancia."
            elif all(costos_medios[i] >= costos_medios[i + 1] for i in range(len(costos_medios) - 1)):
                tendencia_costo = "decrece monotónicamente (revisar la dificultad relativa de las instancias)."
            else:
                tendencia_costo = "no sigue una tendencia clara entre instancias."

            if all(tiempos_medios[i] <= tiempos_medios[i + 1] for i in range(len(tiempos_medios) - 1)):
                tendencia_tiempo = "el tiempo de ejecución escala correctamente con la dificultad."
            else:
                tendencia_tiempo = "el tiempo de ejecución no escala de forma monótona entre instancias."

            f.write(f"  - Tendencia de costo     : {tendencia_costo}\n")
            f.write(f"  - Tendencia de tiempo    : {tendencia_tiempo}\n")



            f.write("\n")

# Entrada por teclado
def limpiar_ruta(ruta):
    """Elimina espacios y comillas accidentales al pegar una ruta."""
    return ruta.strip().strip('"').strip("'")

"""# Función Main"""

def main():
    global universo
    global subconjuntos

    print("Set Covering Problem - Simulated Annealing")
    print(f"Semilla base: {SEMILLA} | Offsets por instancia: {OFFSET_INSTANCIA}")
    print("Seleccione modo de ejecución:")
    print("1. Probar con una instancia específica")
    print("2. Probar con las 3 instancias predefinidas\n")

    opcion = input("Opción [1/2]: ").strip()

    instancias_a_ejecutar = []

    if opcion == "1":
        print("\nIngrese la ruta del archivo .txt con la instancia SCP.")
        ruta_archivo = limpiar_ruta(input("Ruta del archivo: "))

        if ruta_archivo == "":
            raise ValueError("Debe ingresar una ruta de archivo.")

        nombre_instancia = input("Nombre para identificar la instancia [instancia_unica]: ").strip()

        if nombre_instancia == "":
            nombre_instancia = "instancia_unica"

        instancias_a_ejecutar.append((nombre_instancia, ruta_archivo))

    elif opcion == "2":
        print("\nSe ejecutarán las 3 instancias predefinidas:")
        for nombre_instancia, ruta_archivo in instancias_predefinidas:
            print("-", nombre_instancia, ":", ruta_archivo)

        instancias_a_ejecutar = instancias_predefinidas.copy()

    else:
        raise ValueError("Opción inválida. Debe seleccionar 1 o 2.")

    todos_los_resultados = []
    resumenes = []

    for nombre_instancia, ruta_archivo in instancias_a_ejecutar:
        print("\n=======================================================")
        print("Cargando instancia:", nombre_instancia)
        print("Ruta:", ruta_archivo)

        universo, subconjuntos = leer_instancia_scp(ruta_archivo)

        print("Instancia cargada correctamente.")
        print("Elementos del universo:", len(universo))
        print("Cantidad de subconjuntos:", len(subconjuntos))
        print("Ejecutando", n_ejecuciones, "veces...\n")

        resumen = ejecutar_experimentos(nombre_instancia)

        imprimir_resumen_resultado(resumen)

        resumenes.append(resumen)
        todos_los_resultados.extend(resumen["filas_resultados"])

    guardar_resultados_csv(todos_los_resultados, "resultados_detalle.csv")
    guardar_resumen_csv(resumenes, "resultados_resumen.csv")
    guardar_boxplot_csv(resumenes, "boxplot_datos.csv")
    guardar_convergencia_csv(resumenes, "convergencia_detalle.csv")
    guardar_analisis_txt(resumenes, "analisis_resultados.txt")

    # CSV por instancia separado
    archivos_por_instancia = guardar_csv_por_instancia(resumenes)

    # Exportación a Excel
    ruta_xlsx = guardar_resultados_xlsx(todos_los_resultados, resumenes)

    archivos_graficos = plottear_graficos(resumenes)

    print("\nArchivos generados:")
    print("- resultados_detalle.csv")
    print("- resultados_resumen.csv")
    print("- boxplot_datos.csv")
    print("- convergencia_detalle.csv")
    print("- analisis_resultados.txt")

    for archivo in archivos_por_instancia:
        print("-", archivo)

    if ruta_xlsx:
        print("-", ruta_xlsx)

    print("\nSemillas que produjeron la mejor solución por instancia:")
    for resumen in resumenes:
        print(
            f"- {resumen['instancia']}: semilla = {resumen['semilla_mejor_global']}, "
            f"costo = {resumen['mejor_costo_global']}"
        )

    for archivo in archivos_graficos:
        print("-", archivo)

    return archivos_graficos

"""# Ejecución Main"""

if __name__ == "__main__":
    archivos_graficos = main()
    mostrar_graficos_generados(archivos_graficos)

"""## Rutas relativas de Instancias de Prueba tras "git clone"
"""

#/content/TareaOptimizacionFinal/Instancias/Complejas/01_facil.txt
#/content/TareaOptimizacionFinal/Instancias/Complejas/02_medio.txt
#/content/TareaOptimizacionFinal/Instancias/Complejas/03_dificil.txt
#/content/TareaOptimizacionFinal/Instancias/Simples/SCP_simple1.txt
#/content/TareaOptimizacionFinal/Instancias/Simples/SCP_simple2.txt
